package com.ecommerce.model;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

@Data
@Entity
@NoArgsConstructor
@Table(name = "Voucher")
public class Voucher {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long voucherId;

  /**
   * Auto-generated by a PostgreSQL trigger as: 'VCH-' || LPAD(VoucherID::varchar, 6, '0')
   * Managed by the DB — do not insert/update from application.
   */
  @Column(length = 10, unique = true, insertable = false, updatable = false)
  private String code;

  @Column(nullable = false)
  private LocalDateTime startedTime;

  @Column(nullable = false)
  private LocalDateTime expiredTime;

  @Column(nullable = false)
  private Integer currentUsedNumber = 0;

  @Column(nullable = false)
  private Integer maxUsedNumber = 1;

  @Column(nullable = false)
  private Integer minMoneyValue = 0;
}
